[[redirects]]
  from = "/*"
  to = "/"
  status = 200
  force = false

[[redirects]]
  from = "/*"
  to = "/about"
  status = 200
  force = false

[[redirects]]
  from = "/*"
  to = "/contact"
  status = 200
  force = false

[[redirects]]
  from = "/*"
  to = "/product"
  status = 200
  force = false

